DROP TABLE IF EXISTS USER_DETAILS;  
CREATE TABLE USER_DETAILS ( 
id BIGINT PRIMARY KEY,
userName VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
is_active BOOLEAN,
roles VARCHAR(200) NOT NULL
);
commit;